RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "D:\Keil_V5\UV4\UV4.exe"
UVPROJX_LOC := "D:\STEM32\f767\SY15\Projects\MDK-ARM\atk_f767.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'

